- name: app setup 
  import_role:
    name: common 
    tasks_from: app-setup

- name: nodejs setup
  import_role:
    name: common 
    tasks_from: nodejs

- name: systemd service 
  import_role:
    name: common 
    tasks_from: systemd-setup 

- name: enable and start 
  service: 
    name: cart 
    enabled: yes 
    state: restarted 